### ISSUE TITLE
Humdity Superclasses missing

### ISSUE THREAD

**Issue by drseb** [pato-ontology/pato#105]
Hi,

in pato-edit.obo I see that _PATO:0015010 increased humidity_ and _PATO:0015011 decreased humidity_ do not have any superclasses. Is this intended?
If not, they could be subclasses of _PATO:0002300 increased quality_ and  _PATO:0002301 decreased quality_ respectively.

**Comment by drseb** [comment]
The same question applies to:

"increased degree of illumination" ,"decreased degree of illumination" ,"increased combustibility" ,"decreased combustibility"

**Comment by pbuttigieg** [comment]
Aren't those superclasses filled by inference? The asserted superclass
would probably be some sort of "moistness " quality for humidity

**Comment by drseb** [comment]
You're right. In the release-version they have the inferred superclasses. Thanks
