### ISSUE TITLE
NTR: stability/ decreased stability

### ISSUE THREAD

**Issue by sabrinatoro** [pato-ontology/pato#113]
Hello, 
I would like to request new terms: 

1)New term: stability
- child of "structure"  (PATO:0000141)
- parent of "decreased stability" (NTR below)
- definition : quality, state, or degree of being stable (definition from Merriam-Webster)

2) New term: decreased stability 
- synonym: unstable 
- child of "stability" (NTR above)
- definition: a stability which is relatively low

Example: These terms could be used in an EQ statement in which E is a molecular complex (term from GO-CC), or an anatomical structure.

Thank you

**Comment by cmungall** [comment]
Related: https://biology.stackexchange.com/questions/56568/how-to-quantify-the-stability-of-a-protein-complex

**Comment by cmungall** [comment]
Following from #112 I'd be inclined to treat stability not as a type of structure but rather as a disposition of a material entity to retain a particular structure or homeostatic set of structures.

Does the parentage matter to you or do you mostly need the term IDs?

**Comment by cmungall** [comment]
it's tempting to treat as 

add synonyms to

```
. PATO:0001662 ! fragility * 
 % PATO:0001362 ! fragile
  % PATO:0002056 ! decreased fragility
  % PATO:0002055 ! increased fragility
 % PATO:0001716 ! non-fragile
```

But I think in this case it's better to make the new class and relate it to this hierarchy via other means, fragility has many other connotations beyond not-stable

**Comment by sabrinatoro** [comment]
Indeed, the parentage didn't matter much to me, as I mostly needed the terms. 
Thank you!
