### ISSUE TITLE
NTR: elite

### ISSUE THREAD

**Issue by nlwashington** [pato-ontology/pato#126]
Name: elite quality
Definition: having the qualities or abilities of a select part of a group that is superior to the rest of the group

Where should this fit? Perhaps as a subclass of "increased quality"?  Though I am having a hard time fitting this into the structure of PATO in general, as it could be a refinement of nearly all __increased__ terms.

**Comment by pbuttigieg** [comment]
Hmm, this seems like risky territory: Does 'eliteness' inhere in a bearer the same way 'blueness' does? The suggestion, then, is that it's internally grounded rather than an externally grounded value assignment. I would suggest this be modeled more like a BFO:role.

**Comment by nicolevasilevsky** [comment]
@pbuttigieg should I open a ticket on the BFO tracker?

**Comment by nicolevasilevsky** [comment]
(not sure if this is still needed or not though)

**Comment by cmungall** [comment]
I don't think the request is to have the term in BFO

If these are still required then I would suggest an autogenerated application ontology outside PATO, with DPs

`member of group with {highest,lowest}<quality>`

these could be roles that inhere in the group member, there would be some other relationship to the group.

We could also precoordinate some groups, e.g

`member of <species> with {highest,lowest}<quality>`

also

`<species> with {highest,lowest} average <quality>, measured in adult`

and 
`<species> with {highest,lowest} average <quality> <entity>, measured in adult`

e.g. giraffes and neck length

**Comment by nicolevasilevsky** [comment]
Ah, I see. I'm not sure if this is still required. 
@nlwashington if you get this - can you comment?

**Comment by nicolevasilevsky** [comment]
I think we can close this, please reopen if needed.
