### ISSUE TITLE
new term: posteroventral orientation

### ISSUE THREAD

**Issue by wdahdul** [pato-ontology/pato#134]
definition:        An orientation quality inhering in a bearer by virtue of the bearer having a position that is directed posteroventrally.     
is_a: orientation
exact synonym: posteroventrally oriented

**Comment by wdahdul** [comment]
I couldn't find this term in the new release.

**Comment by shawntanzk** [comment]
Term is present at https://www.ebi.ac.uk/ols/ontologies/pato/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPATO_0040005
