### ISSUE TITLE
How to represent 'normal rate' using PATO?

### ISSUE THREAD

**Issue by zhengj2007** [pato-ontology/pato#139]
PATO has 'normal' and 'rate'. If I want to indicate an entity has quality 'normal rate', how can I represent it using a PATO term? Is it the correct way that to create a new qualifier term like 'normal rate':  http://purl.obolibrary.org/obo/APO_0000252?

Thanks,

Jie

**Comment by zhengj2007** [comment]
@cmungall Any suggestion on it? Shall we request 'normal rate' in this case?

Thanks!

**Comment by cmungall** [comment]
This could be post-coordinated. But it's not consistent to 
pre-coordinate inc/dec and not have one for no change, what do others 
think?

**Comment by mah11** [comment]
FYPO has a bunch of "normal rate of process" terms that we've done as PATO:rate + PATO:normal + GO BP, e.g. FYPO:0005899 "normal rate of actin filament-based movement" (during vegetative growth) is:


    rate
     and (happens_during some 'single-celled organism vegetative growth phase')
     and (inheres_in some 'actin filament-based movement')
     and (qualifier some normal)

I think this is based on advice from George but it's been a while ... we chatted about this among other things when we were getting FYPO development started. We could switch to a pre-coordinated PATO class but we haven't clamored for one because this seems to be working for us.

**Comment by gkoutos** [comment]
> On 19 Dec 2017, at 16:17, Chris Mungall <notifications@github.com> wrote:
> 
> This could be post-coordinated. But it's not consistent to 
> pre-coordinate inc/dec and not have one for no change, what do others 
> think?

Yes - we decided to pre-coordinate on a need to have basis. Luke - could you please add these terms ?

Many thanks !

George

**Comment by zhengj2007** [comment]
@gkoutos Thank!

We will populate a list of pre-coordinate terms we need and submit to PATO.

Thanks!

**Comment by gkoutos** [comment]
> On 20 Dec 2017, at 16:33, jie zheng <notifications@github.com> wrote:
> 
> @gkoutos Thank!
> 
> We will populate a list of pre-coordinate terms we need and submit to PATO.

Would be great - thank you !

George

**Comment by cmungall** [comment]
On 20 Dec 2017, at 8:23, gkoutos wrote:

>> On 19 Dec 2017, at 16:17, Chris Mungall <notifications@github.com> 
>> wrote:
>>  
>> This could be post-coordinated. But it's not consistent toÂ 
>> pre-coordinate inc/dec and not have one for no change, what do 
>> othersÂ 
>> think?
>
> Yes - we decided to pre-coordinate on a need to have basis. Luke - 
> could you please add these terms ?
>
> Many thanks !
>
> George

Remember and add the axioms for these. We should probably create DOSDPs 
for PATO

**Comment by nicolevasilevsky** [comment]
can this ticket be closed?
@reality

**Comment by zhengj2007** [comment]
I think so. Our issue is solved.
