### ISSUE TITLE
Propose move the terms for 'response to', 'resistance to' and 'sensitivity toward' to be children of 'organismal quality'

### ISSUE THREAD

**Issue by cooperl09** [pato-ontology/pato#149]
These classes (and their child classes) would better fit as children of organismal quality, rather than physical object quality.
organismal quality (PATO:0001995) : A quality that inheres in an entire organism or part of an organism. [ PATOC:CJM ] 

- response to (PATO:0000077)  
- resistance to (PATO:0001046)
- sensitivity toward (PATO:0000085)

**Comment by cmungall** [comment]
can;t they apply to cells?

**Comment by cooperl09** [comment]
Cells are either an organism themselves, or part of an organism, so the def'n fits, Right?

**Comment by cmungall** [comment]
the original idea was that organisms is at the organism level

if it pertains to parts of organisms then biomolecular and cellular 
qualities are organismal qualities, which renders the top level 
distinction a bit useless

overall I'm not sure how important these top levels are anyway
