### ISSUE TITLE
NTR: Various measurements of the human body

### ISSUE THREAD

**Issue by Aqua1ung** [pato-ontology/pato#150]
My first impulse was to submit these to OBA. Should you guys have a better idea, I'd like to hear it.

**Editor preferred term:** axillary temperature
**Textual definition:** Temperature of a human's axilla.
**Definition source:** EuPath team
**Proposed parent:** temperature
**Example of usage:** 
**Submitted by:** EuPath team

**Editor preferred term:** mid-upper arm circumference (MUAC)
**Textual definition:** Circumference of the mid-upper arm of a human subject.
**Definition source:** EuPath team
**Proposed parent:** circumference
**Example of usage:** 
**Submitted by:** EuPath team

**Editor preferred term:** respiratory rate per minute (RRPM)
**Textual definition:** Rate of the respiratory cycle of an organism.
**Definition source:** EuPath team
**Proposed parent:** rate (161)
**Example of usage:** 
**Submitted by:** EuPath team

**Comment by mellybelly** [comment]
yep please make OBA ticket

On Mar 9, 2018, at 8:33 AM, Cristian Cocos <notifications@github.com<mailto:notifications@github.com>> wrote:


My first impulse was to submit these to OBA. Should you guys have a better idea, I'd like to hear it.

Editor preferred term: axillary temperature
Textual definition: Temperature of a human's axilla.
Definition source: EuPath team
Proposed parent: temperature
Example of usage:
Submitted by: EuPath team

Editor preferred term: mid-upper arm circumference (MUAC)
Textual definition: Circumference of the mid-upper arm of a human subject.
Definition source: EuPath team
Proposed parent: circumference
Example of usage:
Submitted by: EuPath team

Editor preferred term: respiratory rate per minute (RRPM)
Textual definition: Rate of the respiratory cycle of an organism.
Definition source: EuPath team
Proposed parent: rate (161)
Example of usage:
Submitted by: EuPath team

**Comment by nicolevasilevsky** [comment]
@Aqua1ung do you mind if I close this ticket? Did you make a ticket in OBA?

**Comment by Aqua1ung** [comment]
Yes, feel free to close it.
