### ISSUE TITLE
There is a faulty is_a relationship in the current obo file

### ISSUE THREAD

**Issue by cmpich** [pato-ontology/pato#151]
id: PATO:0001816
name: increased fatigability
def: "A fatigability which is relatively high." [PATOC:GVG]
subset: disposition_slim
subset: value_slim
synonym: "high fatigability" EXACT []
is_a: PATO:0001815 ! fatigability
is_a: PATO:1778
relationship: is_opposite_of PATO:0001817 ! decreased fatigability

the second is_a line should contain either a valid pato term or should be removed.

**Comment by nicolevasilevsky** [comment]
@cmungall When I try to save any changes to this ontology, my protege freezes and is stuck in the trying to save mode. I have to force quit.

**Comment by cmungall** [comment]
I just did this using the github editor ut we should investigate the protege issue

**Comment by nicolevasilevsky** [comment]
thanks!

**Comment by cmungall** [comment]
Looks like it came from @reality when fixing an issue I had introduced earlier... https://github.com/pato-ontology/pato/commit/a50b918c919d769563cfd4a48a2ce336a34d401e

**Comment by cmungall** [comment]
@reality looks like you made a few edits on Dec 22 2017:

This seems OK:
https://github.com/pato-ontology/pato/commit/632f32c97815d2baf8d2a9ae330a7513e8d02a4b

But I don't understand this one, there appears to be two mistakes:
https://github.com/pato-ontology/pato/commit/a50b918c919d769563cfd4a48a2ce336a34d401e

First the zero-paddings disappeared. I want to check this isn't something in your toolchain that is going wrong?

Second, the equivalence axioms are removed. All inc/dec terms should follow the same design pattern. Was there a reason for this?

**Comment by cmpich** [comment]
The obo file from this location (redirect from the purl: http://purl.obolibrary.org/obo/pato.obo) has not changed:
https://raw.githubusercontent.com/pato-ontology/pato/master/pato.obo
and still shows the faulty line.

**Comment by cmungall** [comment]
Yep, will be fixed next release, v soon

**Comment by nicolevasilevsky** [comment]
@cmpich We just released a new version of PATO, so you should see this fix now.

**Comment by cmpich** [comment]
Great, thanks. It's working again 👍
