### ISSUE TITLE
new term trough shaped

### ISSUE THREAD

**Issue by wdahdul** [pato-ontology/pato#185]
synonym: trough like (also trough-like, trough-shaped)

def: A concave 3-D shape quality inhering in a bearer by virtue of the bearer's shape resembling that of a trough, being narrow, long, and boxlike in shape. See: http://www.dictionary.com/browse/trough

is_a: concave 3-D shape (PATO:0002008)

**Comment by nicolevasilevsky** [comment]
I will add this next week unless anyone objects
