### ISSUE TITLE
new term dorsomedial orientation

### ISSUE THREAD

**Issue by wdahdul** [pato-ontology/pato#188]
synonym: dorsomedially directed

def: An orientation quality inhering in a bearer by virtue of the bearer having a position that is directed dorsomedially.

is_a: orientation (PATO:0000133)

**Comment by nicolevasilevsky** [comment]
I will add this next week unless anyone objects

**Comment by nicolevasilevsky** [comment]
added this term with primary label 'dorsomedial orientation' and 'dorsomedially directed' as an exact synonym
