### ISSUE TITLE
new term fringed

### ISSUE THREAD

**Issue by wdahdul** [pato-ontology/pato#193]
New term request: fringed
Suggested is_a relationship: 'shape' or 'edge shape'

def: A shape quality inhering in a bearer by virtue of the bearer's having an ornamental border consisting of short straight or twisted threads or strips hanging from cut or raveled edges or from a separate band. Def ref: https://www.merriam-webster.com/dictionary/fringe

**Comment by nicolevasilevsky** [comment]
I will add this next week unless anyone has any objections
