### ISSUE TITLE
hypsodont and brachydont

### ISSUE THREAD

**Issue by wdahdul** [pato-ontology/pato#20]
These are terms that describe the shape of mammalian teeth:
- hypsodont
  Definition: Hypsodont dentition is characterized by high-crowned teeth and enamel which extends far past the gum line, which provides extra material for wear and tear.  
  is_a: shape
  include axiom: hypsodont inheres_in some ('tooth crown' and bearer_of 'decreased 
  height')
- brachydont
  synonym: brachyodont
  is_a: shape
  include axiom: brachydont inheres_in some ('tooth crown' and bearer_of 'increased 
  height')

Definition: Brachyodont is a type of dentition characterized by low-crowned teeth. Human teeth are brachydont.

definitions from: Damuth and Janis, 2011 Biological Reviews 86:733-758
doi: 10.1111/j.1469-185X.2011.00176.x

**Comment by nicolevasilevsky** [comment]
@wdahdul I think Uberon is now imported into Pato, and I think we can MIREOT any terms that are needed. What terms do you need?

**Comment by wdahdul** [comment]
Looking back at this one, I don't think it's necessary to link to uberon terms (at least for phenoscape). Ok to close this item.

**Comment by nicolevasilevsky** [comment]
thanks!
