### ISSUE TITLE
Rename PATO:quality to PATO:phenotypic quality

### ISSUE THREAD

**Issue by matentzn** [pato-ontology/pato#216]
To avoid the annoying nameclashes we get all the time when working with PATO and BFO quality in Protege (label based rendering).. Thoughts?

**Comment by nicolevasilevsky** [comment]
that could work! I have no objections

**Comment by cmungall** [comment]
Note that PATO is being used in very different contexts, e.g. in OBI to say
a sample is frozen. Stretching it to say that is a phenotype.

I think the PATO root is actually the more general 'characteristic' (see RO
PR). PATO's 'physical object quality' is BFO quality (or really "quality or
disposition")

**Comment by matentzn** [comment]
Well that pretty much makes this change impossible. :) Thanks for letting us know!
