### ISSUE TITLE
Increased and decreased terms for new rate subclasses

### ISSUE THREAD

**Issue by Clare72** [pato-ontology/pato#241]
Related to #221 
We also need 'increased ...' and 'decreased ...' for the new rate subclasses (after PR #228 is merged)

 - increased rate of occurrence
 - increased rate of continuous process
 - decreased rate of occurrence
 - decreased rate of continuous process

For the new term definitions we can just add 'Increase in...' or 'Decrease in...' to the beginning of the text definitions for the rates.
Relationships can follow the same pattern as 'increased frequency' and 'decreased frequency'

**Comment by mah11** [comment]
I think we would use all of these in FYPO.

**Comment by mah11** [comment]
I need increased & decreased rate of continuous process, so I'm doing a PR for these ...
