### ISSUE TITLE
relate response_to and sensitivity_toward branches

### ISSUE THREAD

**Issue by dosumis** [pato-ontology/pato#244]
These are not currently related:

![image](https://user-images.githubusercontent.com/112839/58271174-5a426800-7d83-11e9-8fbf-6fb8ef4355a4.png)

![image](https://user-images.githubusercontent.com/112839/58271187-64fcfd00-7d83-11e9-9388-158acfd519d4.png)

I think they should be.

**Comment by matentzn** [comment]
@mah11 @sbello  Could you offer your opinion?

**Comment by nicolevasilevsky** [comment]
Discussed this on 10/08/20 call and decided this was no longer needed.
