### ISSUE TITLE
Multi-colored (PATO:0001533) should be a morphology quality, rather than a position (PATO:0000140)

### ISSUE THREAD

**Issue by cooperl09** [pato-ontology/pato#247]
We are getting some weird inferences because multi-colored (PATO:0001533) is a child of  position (PATO_0000140).  This really doesn't make any sense. It seems better for color pattern (PATO_0000019) to be a morphology quality. 

multi-colored >> color pattern >> spatial pattern >> position

I can see some justification for spatial pattern >> position, in regards to patterning of limbs, branches, etc, but color patterns are a morphological feature.

**Comment by nicolevasilevsky** [comment]
should the PATO_0000019 'color pattern' be moved to a child of morphology?

**Comment by cmungall** [comment]
Do we have an over-arching ticket for morphology? There was a lot of talk about this at the workshop, did that get transcribed anywhere? I think it is good to do this in a coordinated way with approval from all stakeholders. It seems we are going for a very general definition of morphology now?

(either way, multi-colored as a child of position is weird and clearly a mistake, so maybe go ahead with this one for now?)

**Comment by nicolevasilevsky** [comment]
there is this ticket: https://github.com/pato-ontology/pato/issues/239

**Comment by matentzn** [comment]
@dosumis is this fixed now?

**Comment by dosumis** [comment]
> We are getting some weird inferences because multi-colored (PATO:0001533) is a child of position (PATO_0000140). This really doesn't make any sense. It seems better for color pattern (PATO_0000019) to be a morphology quality.

Rather than moving 'color pattern', I think we should move its parent class 'spatial pattern' from position to morphology. Any objections?
