### ISSUE TITLE
spatial distribution of a process

### ISSUE THREAD

**Issue by dosumis** [pato-ontology/pato#252]
Some process, for example bone mineralization during development, follow stereotypical spatial distribution patterns that may be altered in some phenotypes.  We need a term for recording these phenotypes

**Comment by mah11** [comment]
Oooh, this looks like it could also be useful for some phenotypes we have in FYPO where the spatial extent over which a certain type of chromatin forms (e.g. heterochromatin or CENP-A containing nucleosomes) is altered in a mutant.

Could we use increased' and 'decreased' subtypes of this PATO:new to logically define phenotypes like these? E.g.

id: FYPO:0004322
name: decreased spatial extent of CENP-A containing nucleosome assembly
def: "A cellular process phenotype observed in the vegetative growth phase of the life cycle in which nucleosomes containing the histone H3 variant CenH3 (also called CENP-A; Cnp1 in S. pombe) are assembled over a smaller portion of the centromeric region of the chromosome than normal. CENP-A-containing nucleosomes are normally assembled into chromatin around centromeres, encompassing the central core and centromeric inner repeat regions." [GO:0034080, PMID:24710126, PomBase:mah, PomBase:vw]

id: FYPO:0004749
name: increased spatial extent of subtelomeric heterochromatin assembly
def: "A cellular process phenotype observed in the vegetative growth phase of the life cycle in which heterochromatin is assembled over a larger portion of the subtelomeric region of the chromosome than normal." [GO:0031509, PMID:25774602, PomBase:mah]


... or even ones like this?

id: FYPO:0005463
name: decreased spatial extent of interphase microtubule polymerization
def: "A cellular process phenotype observed in the vegetative growth phase of the life cycle in which cytoplasmic microtubule polymerization, i.e. the addition of tubulin dimers to the plus end of a cytoplasmic microtubule during interphase of the mitotic cell cycle, does not continue until microtubules reach the ends of the cell." [PMID:12894167, PomBase:mah]

We also have some 'normal' spatial extents in FYPO ...

**Comment by dosumis** [comment]
> Could we use increased' and 'decreased' subtypes of this PATO:new to logically define phenotypes 

All look reasonable to me.  Do you have time to add and make a pull request?

**Comment by dosumis** [comment]
(I've merged the original pull request - so the subterms should be on a new branch/PR.  For tracking purposes, I think it would be best to paste above into new ticket and close that from a commit on the pull request)
