### ISSUE TITLE
Add increased/decreased (broadened/narrowed?) spatial distribution of process

### ISSUE THREAD

**Issue by dosumis** [pato-ontology/pato#254]
Subtypes of `spatial distribution of a process` (see #252)

Examples from @mah11:

E.g.

id: FYPO:0004322
name: decreased spatial extent of CENP-A containing nucleosome assembly
def: "A cellular process phenotype observed in the vegetative growth phase of the life cycle in which nucleosomes containing the histone H3 variant CenH3 (also called CENP-A; Cnp1 in S. pombe) are assembled over a smaller portion of the centromeric region of the chromosome than normal. CENP-A-containing nucleosomes are normally assembled into chromatin around centromeres, encompassing the central core and centromeric inner repeat regions." [GO:0034080, PMID:24710126, PomBase:mah, PomBase:vw]

id: FYPO:0004749
name: increased spatial extent of subtelomeric heterochromatin assembly
def: "A cellular process phenotype observed in the vegetative growth phase of the life cycle in which heterochromatin is assembled over a larger portion of the subtelomeric region of the chromosome than normal." [GO:0031509, PMID:25774602, PomBase:mah]

... or even ones like this?

id: FYPO:0005463
name: decreased spatial extent of interphase microtubule polymerization
def: "A cellular process phenotype observed in the vegetative growth phase of the life cycle in which cytoplasmic microtubule polymerization, i.e. the addition of tubulin dimers to the plus end of a cytoplasmic microtubule during interphase of the mitotic cell cycle, does not continue until microtubules reach the ends of the cell." [PMID:12894167, PomBase:mah]

We also have some 'normal' spatial extents in FYPO ...

**Comment by mah11** [comment]
@dosumis Any objection if I use these names and text definitions?

name: decreased spatial extent of a process
def: A spatial distribution of a process in which the process occupies a smaller length, area, or volume than the reference process. For example, heterochromatin may form over a shorter length of a chromosome in a mutant than in wild type.

name: increased spatial extent of a process
def: A spatial distribution of a process in which the process occupies a greater length, area, or volume than the reference process. For example, heterochromatin may form over a greater length of a chromosome in a mutant than in wild type.
