### ISSUE TITLE
NTR: Diandrous and monandrous

### ISSUE THREAD

**Issue by diatomsRcool** [pato-ontology/pato#257]
This will be tricky because diandrous and monandrous mean different things for plants and animals. How should we differentiate in the label?

Preferred Label
Diandrous
Monandrous

Definition
Diandrous (plant): having two stamens
Monandrous (plant): having one stamen
Diandrous (animal): possessing two different types of males
Monandrous (animal): having only one type of male

Parent Class
The plant terms should be subclasses of 'phenotypic sex'
the animal terms should be subclasses of 'mixed sex'

Attribution
http://orcid.org/0000-0002-2908-3327

Notes
There is also diandry: fertilization of an egg by two sperm.

**Comment by ramonawalls** [comment]
I don't think these labels should include "(plant)". These terms are only used in plants, which is clear from the definition, so no need to clarify the label. I will make the change. Also updating the wording of the definition slightly.

**Comment by ramonawalls** [comment]
To clarify the animal definition of diandrous and monandrous (which I think are rarely used, if ever), I suggest instead using the more common terms protandrous and protogynous. These are generally qualities of an organism, so I will move them to be subclasses of phenotypic sex, rather than mixed sex, so they can inhere in either an organism or a population or species.

**Comment by ramonawalls** [comment]
I will also add a term for sequential hermaphrodite (subclass of hermaphrodite) that will be a parent of these terms.

**Comment by ramonawalls** [comment]
I deleted the diandrous and monandrous terms created by @nicolevasilevsky and added new terms for protogynous and protandrous. @diatomsRcool, if you still need terms for populations with two types of males or one type of male for EOL, let me know.

**Comment by ramonawalls** [comment]
Fixes with PATO PR https://github.com/pato-ontology/pato/pull/350
