### ISSUE TITLE
sex-specific terms

### ISSUE THREAD

**Issue by Clare72** [pato-ontology/pato#261]
We would like terms for 'sex-specific', 'male-specific' and 'female-specific' to use in the Drosphila Anatomy Ontology to classify anatomical entities present only in one sex. These can have 'sexually dimorphic' as a parent.

**Comment by dosumis** [comment]
See https://github.com/FlyBase/drosophila-anatomy-developmental-ontology/issues/599 for discussion of ontology modelling sex specific anatomical structures.
