### ISSUE TITLE
Standardise orcids in DBxrefs

### ISSUE THREAD

**Issue by dosumis** [pato-ontology/pato#263]
As I understand it, bare URLs are discouraged in xrefs.  We should instead use a stand Curie.  In the case of orcids => 

https://orcid.org/0000-0003-4148-4606 

-> 

orcid:0000-0003-4148-4606

(although expansion should probably be registered here: https://github.com/geneontology/go-site/edit/master/metadata/db-xrefs.yaml as this seems to have become the standard reference for xrefs.)

**Comment by matentzn** [comment]
>  bare URLs are discouraged in xrefs

I would be interested to see why; all the other phenotype ontologies now use the full IRIs here.. :/ This should be discussed on OBO foundry level I think.

**Comment by dosumis** [comment]
Maybe we could make an exception for ORCIDs, but xrefs in OBO are meant to be DB:acc.  Where DB can be expanded to a base URL that makes them CURIES. 

I've spent a long time stripping out full URLs from xrefs in other projects (VFB, GO).  They are a pain in the ass for linking gracefully in display.

**Comment by matentzn** [comment]
@anitacaron can you close this if it is done?
