### ISSUE TITLE
Refactor imports

### ISSUE THREAD

**Issue by dosumis** [pato-ontology/pato#269]
pato-edit.obo currently has no import statments. It should have import statements for:

pato_ext.owl
imports/...

pato_ext.owl currently imports pato! AND various import files.  These import statments should be removed.

All URLs and cataolog xml need to be checked.

Note by importing pato_ext.owl we will be taking pato out of EL.  However, the aim of this ext file was always to have annotations for axioms outside of EL so that they could be selected easily.  More discussion needed.

Note - state of import generation from Makefile needs to be investigated too.

**Comment by matentzn** [comment]
All I can do for now is done [here](https://github.com/pato-ontology/pato/pull/270).

We need to schedule a 1-on-1 to review this, because the changes to the releases are significant (redundancy stripping has the most impact, followed by equivalent class stripping).
