### ISSUE TITLE
Unify all attribution to ORCID

### ISSUE THREAD

**Issue by matentzn** [pato-ontology/pato#278]

**Comment by matentzn** [comment]
This is the related OMO thread:

https://github.com/information-artifact-ontology/ontology-metadata/issues/60

My suggestion:

can we unify on dc:contributor with orcid moving forward.

- [ ] @shawntanzk raise at CL meeting and get people to object or agree on the ticket

**Comment by shawntanzk** [comment]
General agreement to do this for CL and Uberon
Add a requirement for dc:contributor
