### ISSUE TITLE
Need to standardise created by annotations

### ISSUE THREAD

**Issue by matentzn** [pato-ontology/pato#281]
Either oio:created_by or dc:creator. Opinions welcome. @nicolevasilevsky @sbello what do you use usually? HP/MP/Mondo?

**Comment by sbello** [comment]
The MP uses the default setting in protege for the New Entities metadata, see screenshot below 
![prot_metadata](https://user-images.githubusercontent.com/10979793/67958179-1f175100-fbcd-11e9-9f54-58e0ead564dc.png)

**Comment by nicolevasilevsky** [comment]
We do the opposite for HP and Mondo:
![image](https://user-images.githubusercontent.com/6722114/67990128-2dc42f00-fbf2-11e9-928b-42b01ccf596f.png)

**Comment by sbello** [comment]
I'm guessing that what you're using @nicolevasilevsky is what GO uses as well, yes? If so we can change what the MP uses moving forward. If we do and there is an easy way to change the existing ones please let me know.

**Comment by nicolevasilevsky** [comment]
Yes, I believe this is what GO uses (and that is why we started using it.)

**Comment by matentzn** [comment]
If we decide on that @sbello make a ticket and assign it to me. It is super easy (string replace).

**Comment by anitacaron** [comment]
Related #278
