### ISSUE TITLE
undefined subset ro-eco

### ISSUE THREAD

**Issue by balhoff** [pato-ontology/pato#283]
The new PATO release has at least one undefined subset: `ro-eco`. This is causing failures in old OBO parsers.

**Comment by matentzn** [comment]
Thanks jim; i fixed this, also generally for [all of ODK](https://github.com/INCATools/ontology-development-kit/pull/295)! Good you noticed. 

I made a new release with this being fixed:
http://purl.obolibrary.org/obo/pato/releases/2019-11-05/pato.obo

Hope the old OBO parser does not anymore complain..

**Comment by balhoff** [comment]
Thanks! The old OBO parser is getting pretty creaky.

**Comment by matentzn** [comment]
Haha no worries. We will try our best to support everyone.
