### ISSUE TITLE
NTR: parous

### ISSUE THREAD

**Issue by zhengj2007** [pato-ontology/pato#289]
Name | Value
-- | --
Label | parous
Definition | An organismal quality of having successfully reproduced.
Definition source | EFO_0002947 parous
Parent | PATO_0001995 organismal quality

Request by VEuPathDB (https://eupathdb.org/)

**Comment by matentzn** [comment]
Please review why this term does not appear under 'parity' @nicolevasilevsky @zhengj2007

**Comment by matentzn** [comment]
I have done a fresh release now so the term is available. Still would like to know!

**Comment by nicolevasilevsky** [comment]
oh yeah, seems like it should be a child of parity and a parent of multiparous and primiparous.

@zhengj2007 do you agree?

**Comment by nicolevasilevsky** [comment]
(I didn't mean to close this!)

**Comment by zhengj2007** [comment]
According to the definition of the 'parity', it refers to "The number of time that a viviparous organism has given birth.". It's children are 0, 1, or multiple time(s) given birth. The 'parous' is organism successfully reproduced. So, I don't think it is the child of 'parity'. But I think its parent should be more specific. I am happy to add it as child of 'reproductive quality'. I will ask other VEuPathDB people to check which parent is more appropriate.

**Comment by nicolevasilevsky** [comment]
thank you @zhengj2007!

**Comment by zhengj2007** [comment]
@nicolevasilevsky Here is one comment I got from VEuPathDB: "I agree that 'parous' should be inserted as a parent of 'multiparous' and 'primiparous'. I also agree with you that there are some semantic issues with 'parity' being the parent of 'parous'".
I'd like to leave the decision to you and PATO developers for the parent of 'parous'.

**Comment by matentzn** [comment]
I made parous a sibling of parity (under reproductive quality) and added multi and primiparous under parous.

**Comment by zhengj2007** [comment]
@matentzn @nicolevasilevsky Thanks for making the term available for us.

**Comment by zhengj2007** [comment]
Since the parent of the term changes, is it better to update the definition too?
from "An organismal quality of having successfully reproduced." to "A reproductive quality of having successfully reproduced."
@matentzn @nicolevasilevsky Thanks!

**Comment by matentzn** [comment]
I dont think that is necessary; the definition is necessary and sufficient. Or do you think it does not reflect the truth? It just creates an odd dependency if we one day decide to remove it again from reproductive quality for some reason.. I think its better as is but correct me if I am wrong.
