### ISSUE TITLE
NTR: inchworm

### ISSUE THREAD

**Issue by srobb1** [pato-ontology/pato#292]
Could we get an inchworm movement term? 

Some changes in the cilia in planaria cause an inchworm like phenotype. 

It is a behavior, but they have not control over it so maybe it should be a 
physical quality --> mobility --> inchworm.  

I see there is a behavior quality --> movement behavior quality --> circling. 

I am not sure where it fits best.

**parent:**
movement behavioral quality PATO:0002076

or

**parent:**
mobility PATO:0000004

Thanks,
Sofia

**Comment by matentzn** [comment]
As discussed in our meeting, we will add inchworm as a locomtion behaviour to NBO instead.
