### ISSUE TITLE
NTR: patchy pigmentation

### ISSUE THREAD

**Issue by srobb1** [pato-ontology/pato#293]
Would it be appropriate to have a patchy pigmentation as a sibling to increased/decreased pigmentation? 

parent: 
pigmented PATO:0002248

**Comment by matentzn** [comment]
https://www.ebi.ac.uk/ols/ontologies/pato/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPATO_0001608


Is not what you want because it is not really patchy pigmentation..

**Comment by matentzn** [comment]
Not that either:

https://www.ebi.ac.uk/ols/ontologies/pato/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPATO_0000333

**Comment by srobb1** [comment]
Hahah. Funny. I just noticed this isn't the first time I requested this term. It was almost exactly a year from the creation of this request. I am not sure what is with me and pigmentation in January :)

https://github.com/pato-ontology/pato/issues/214
