### ISSUE TITLE
Relax the axiomatisation of prominence

### ISSUE THREAD

**Issue by matentzn** [pato-ontology/pato#297]
Currently we have this:

![image](https://user-images.githubusercontent.com/7070631/74434390-429f9800-4e5a-11ea-97d2-d03d45892031.png)

This causes some [confusion](https://github.com/obophenotype/upheno/issues/510#issuecomment-584346349) as phenotypes with an abnormal prominence of something classify under abnormal position. I vote to simply move the prominence and protruding branches out from under position.

@dosumis @wdahdul @balhoff @sbello

**Comment by nicolevasilevsky** [comment]
what do you think the parent should be then? should it be a child of 'physical quality'?

I'll create a PR for this and tag the folks above.

**Comment by dosumis** [comment]
I'd keep superclass protruding, and move  that under physical quality.
