### ISSUE TITLE
Revise def? - fragmented

### ISSUE THREAD

**Issue by nicolevasilevsky** [pato-ontology/pato#320]
NTR: fragmented
Def: Existing or functioning as though broken into separate parts; disorganized; disunified.
Source: dictionary.com/browse/unfragmented
Parent: PATO_0000141 structure 
@pnrobinson @dosumis @matentzn does this seem like the best parent? Thanks!

Related ticket: https://github.com/obophenotype/human-phenotype-ontology/issues/3889

This is needed for HPO terms like:
HP_0100168 'Fragmented epiphyses'

**Comment by matentzn** [comment]
I wonder whether it could go under [broken](https://www.ebi.ac.uk/ols/ontologies/pato/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPATO_0001444&viewMode=PreferredRoots&siblings=false)?

![image](https://user-images.githubusercontent.com/7070631/81713197-3be6e800-947e-11ea-94c3-fbc9e5e80aca.png)

**Comment by nicolevasilevsky** [comment]
that is what I was wondering too. But the def says existing or functioning as though broken... Is a fragmented bone considered broken, @pnrobinson? Thanks!

**Comment by nicolevasilevsky** [comment]
from @dosumis (on the PR)

I find the definition confusing. What does 'as though broken into pieces mean? I I think that the distinction Peter wants (for bones) is between being in pieces as the result of trauma (shattered) vs being in separate pieces, perhaps due to a developmental defect. This is another example of how we get ourselves in a tangle by not explicitly referring to the comparative nature of phenotypes (fragmented compared to wild-type). I'm OK with merging to provide the term quickly if we can't come up with a better wording now - but if so would like to keep discussion going on the ticket so we fix at some point.
