### ISSUE TITLE
Quantitative versus qualitative traits

### ISSUE THREAD

**Issue by nleguillarme** [pato-ontology/pato#330]
Hi, I am currently working on a schema for a knowledge base of organism traits and interactions, and plan to reuse pato:quality for representing trait types and trait values.

Concerning qualitative traits, suppose I have the following assertion "Taxon A has oviparous reproduction strategy". I guess it translates directly into the following RDF triple : <TaxonA, has_quality, ecocore:oviparous> (with ecocore:oviparous a descendant of pato:'organismal quality').

Now, suppose I have the following assertion "The tail length of Taxon A is 10 cm", it is not clear to me how I can turn this into an RDF triple using OBO ontologies. I guess I can create a triple <TaxonA, has_quality, oba:tail_length>, but how can I tell that the value of the 'tail length' instance is 10 cm ?

Thank you for your help (and please tell me if this not the best place to ask questions about ontologies use).

**Comment by sbello** [comment]
I'd suggest talking to the Rat Genome Database (https://rgd.mcw.edu/) or the AnimalQTL database (https://www.animalgenome.org/cgi-bin/QTLdb/index) groups about this. They capture this sort of information for quantitative trait loci using the vertebrate trait ontology (https://github.com/AnimalGenome/vertebrate-trait-ontology), clinical measurement ontology and a field for the measurement value (I think that is correct).

**Comment by nleguillarme** [comment]
Hi @sbello, and thank you for your answer. I just figured out a way using OBI. Actually, this is one of their example use cases : https://github.com/obi-ontology/obi/wiki/Example_Use_Cases

**Comment by shawntanzk** [comment]
Solution seems to have been found
