### ISSUE TITLE
Suggest revising definitions for length & thickness

### ISSUE THREAD

**Issue by johnwjudkins** [pato-ontology/pato#337]
I am working on definitions for measurement data for anatomical entities, such as ear thickness. I appreciate how PATO has many terms for specific size qualities. However, I think the definitions for '1-D extent', length, width, and thickness could be rewritten to more clearly distinguish these qualities from one another. I would like to suggest for revisions something along these lines:

length - The greatest 1-D extent that inheres in a bearer compared to its extent in other dimensions.

width - The second greatest 1-D extent that inheres in a bearer compared to its extent in other dimensions.

thickness - The smallest 1-D extent that inheres in a bearer compared to its extent in other dimensions.

I think these could apply for both Cartesian and non-Cartesian coordinate systems e.g. thickness of a blood vessel.

**Comment by johnwjudkins** [comment]
Following up. I've improved on the definitions. Now I think only the length and width definitions need to be changed.

length
A 1-D extent that is greater in its dimension than the extent in either of the other two orthogonal dimensions.

width
A 1-D extent in the dimension such that it is greater than the extent in only one of the other two orthogonal dimensions.

**Comment by shawntanzk** [comment]
Hi @johnwjudkins , sorry this didn't get looked at before. 

@nicolevasilevsky @dosumis (please tag anyone else in here that might be interested) - need input on this

I think the proposed changes are over-restrictive, given that the use length, width, and thickness are highly dependent on the situation and perspective. I get that in maths, the longer line must always be the length, but in terms of usage, I'm not sure if this convention is truly followed. 

An example I can think that will break the proposed change is a cube, the length = width = height, therefore with that definition the length and width of a cube cannot exist.

An example of usage where the width might be the longest dimension is when use with height. The height, by definition, has to be the bearer's vertical dimension of extension -> does that mean that if something has a height of X and has a length of with of X +/- Y from variability, the dimension is a length in some instances of the entity but width in another? in which case how do we record this? 

The current definitions allow for both those cases, but admittedly does not do well to distinguish them (I'm guessing that might be by intention - see cube example). 

I think instead what can be done is to add a rdfs:comment "In mathematics length refers to the 1-D extent that is greater in its dimension than the extent in either of the other two orthogonal dimensions. However, this is not always followed" (would like a better comment than that but something with that sort of idea in it?)

**Comment by nicolevasilevsky** [comment]
Hi @shawntanzk adding a comment sounds good. The definitions are not very easy to understand, could we perhaps have a more user-friendly definition? 

See: https://www.merriam-webster.com/dictionary/length

**Comment by shawntanzk** [comment]
I think the marriam-webster dictionary has the same issue as what I mentioned. I think a good compromise would be to make the comment more user-friendly (eg: Length often refers to the longer or longest dimension of an object, however, this is not always true) while keeping the definition as is
