### ISSUE TITLE
Add cellular histological qualities

### ISSUE THREAD

**Issue by dosumis** [pato-ontology/pato#342]
We have a set of terms in CL that should be obsoleted and replaced with PATO terms:

'acidophilic cytoplasm' http://purl.obolibrary.org/obo/CP_0000027
'basophilic cytoplasm' http://purl.obolibrary.org/obo/CP_0000028
'neutrophillic cytoplasm' http://purl.obolibrary.org/obo/CP_0000000
'polychromatophilic cytoplasm' http://purl.obolibrary.org/obo/CP_0000035

Suggested classification definition pattern for these terms:

cellular quality
. - cellular histological quality: A quality inhering in a cell by virtue of its capacity to be stained by specific histological dyes.
. . - cellular acidophilic* histological quality: A cellular quality inhering in a cell by virtue of its capacity to be stained by acidic dyes. Comment: In histopathology this is commonly indicated by pale-pink staining with Wright-Giemsa stain.

**Comment by dosumis** [comment]
Just notices the PATO already has basophilic - but it is clearly in the wrong place.

Def has it inhering in a tissue.  Might be worth broadening to anatomical structure quality - covering cells, tissues, components etc.

**Comment by matentzn** [comment]
@shawntanzk can you deal with this so we can get rid of CP once and for all?
