### ISSUE TITLE
NTR: salinity

### ISSUE THREAD

**Issue by kaiiam** [pato-ontology/pato#345]
Greetings PATO team, Kai Blumberg here from ENVO. 

`Salinity` is commonly measured concept in a variety of environmental disciplines. @cmungall and I would like to add it as a new PATO quality, see the [ENVO liquid water salinity issue](https://github.com/EnvironmentOntology/envo/issues/883). From the discussions there, I would like to propose the following, as a a subclass to PATO:[osmolarity](http://purl.obolibrary.org/obo/PATO_0001655)

> An osmolarity quality inhering in a bearer by virtue of the total amount of ionic salts dissolved in the bearer.

[dbxref1](https://en.wikipedia.org/wiki/Salinity), [dbxref2](https://www.sciencedirect.com/science/article/pii/B9780857096807500012), [dbxref3](https://www.sciencedirect.com/referencework/9780080983004/treatise-on-geochemistry), [dbxref4](https://rwu.pressbooks.pub/webboceanography/chapter/5-3-salinity-patterns/), and [dbxref5](http://db0nus869y26v.cloudfront.net/en/Salinity)

Let me know what you think, I'd be happy to make a PR for this.

**Comment by kaiiam** [comment]
xref https://github.com/bio-ontology-research-group/unit-ontology/issues/31.

**Comment by nicolevasilevsky** [comment]
Sounds great, please go ahead and create a pull request - thanks!

**Comment by kaiiam** [comment]
PR is in @nicolevasilevsky @cmungall see https://github.com/pato-ontology/pato/pull/352.

**Comment by shawntanzk** [comment]
PR has been merged and term has been added

**Comment by kaiiam** [comment]
Thanks @shawntanzk!
