### ISSUE TITLE
use real PATO ids for local object properties

### ISSUE THREAD

**Issue by balhoff** [pato-ontology/pato#355]
PATO defines a few object properties, such as `decreased_in_magnitude_relative_to`, with non-standard IRIs like `http://purl.obolibrary.org/obo/pato#decreased_in_magnitude_relative_to`. These should either be contributed to RO, or be given real PATO numeric identifiers, which would then be resolvable. The hash identifiers frequently cause confusion. See https://github.com/biolink/biolink-model/issues/516.

**Comment by matentzn** [comment]
I agree. These should go into RO!

**Comment by anitacaron** [comment]
Closing in favor of #454
