### ISSUE TITLE
NTR: large basket cell morphology

### ISSUE THREAD

**Issue by shawntanzk** [pato-ontology/pato#370]
**Term:** 
large basket cell morphology

**Definition:**
A basket cell morphology that inheres in neurons that have axonal arbors, composed of frequent short, curvy axonal branches that tend to be near their somata and within the same cortical layer.
PMID:11884355

**Parent Class:**
basket cell morphology #368 

**Other Notes:**
ilxtr:LargeBasketPhenotype

**Comment by tgbugs** [comment]
Reading over this now I'm wondering whether there is a way to link to a type specimen or something like that for these.

**Comment by shawntanzk** [comment]
Not quite sure what you mean by link to a type specimen? Do you mean link it to something like [this](https://github.com/obophenotype/cell-ontology/pull/906)?
