### ISSUE TITLE
NTR: nest basket cell morphology

### ISSUE THREAD

**Issue by shawntanzk** [pato-ontology/pato#371]
**Term:** 
nest basket cell morphology

**Definition:**
A basket cell morphology that inheres in neurons which have simpler dendritic arbors (compared to small or large basket cell morphology), and an axonal plexus of intermediate density, composed of a few long, smooth axonal branches.
PMID:11884355

**Parent Class:**
basket cell morphology #368 

**Other Notes:**
ilxtr:NestBasketPhenotype

**Comment by tgbugs** [comment]
From a provenance point of view, it might be worth noting that this particular morphological classification comes from the Markram lineage. Not sure how such things are tracked (we don't do it explicitly in NPO right now).

**Comment by shawntanzk** [comment]
Happy to add it in an annotation, thoughts @dosumis?

**Comment by dosumis** [comment]
@tgbugs - can you suggest a reference that might make this clear, if the current one does no.

**Comment by tgbugs** [comment]
The PMID listed in the definition is the best reference to use. The Markram lineage is the last author on the paper.
