### ISSUE TITLE
NTR: stellate pyramidal morphology

### ISSUE THREAD

**Issue by shawntanzk** [pato-ontology/pato#379]
**Term:** 
stellate pyramidal morphology

**Definition:**
A pyramidal cell morphology that inheres in neurons which lack a tuft formation but extend to small radial distances forming a star-like shape.
PMID:30715238

**Parent Class:**
pyramidal morphology #376 

**Other Notes:**
ilxtr:StarPyramidalPhenotype

**Comment by dosumis** [comment]
Might be wrong def here?  Same as def to untufted?  What is stellate (star-like) about these?

**Comment by shawntanzk** [comment]
I think the difference is untufted have large radial distance, but either way, I've added "forming a star-like shape" to it to be clearer
