### ISSUE TITLE
NTR: stellate morphology

### ISSUE THREAD

**Issue by shawntanzk** [pato-ontology/pato#382]
**Term:** 
stellate morphology

**Definition:**
A cell morphology that inheres in neurons which have dendritic processes radiating for the cell body that forms a star-like shape
_Note: Need to find ref_

**Parent Class:**
Cell Morphology #364

**Others:**
Stellate Morphology: SAO:9271919883, ILX:0111036

**Comment by tgbugs** [comment]
ILX:0107388 does not map to this directly, it maps to spiny stellate morphology.
