### ISSUE TITLE
NTR: bitufted cell morphology

### ISSUE THREAD

**Issue by shawntanzk** [pato-ontology/pato#384]
**Term:** 
bitufted cell morphology

**Definition:**
A cell morphology that inheres in neurons which have tufts of dendrites extending from two opposite poles of the soma, and have axons that form a plexus which spreads widely, usually descending.
doi:10.1016/b978-0-12-369497-3.10004-4

**Parent Class:**
Cell Morphology #364

**Others:**
ilxtr:BituftedPhenotype

**Comment by tgbugs** [comment]
The `Term:` is mismatched here.

**Comment by shawntanzk** [comment]
my bad, was copying and pasting stuff, and missed that
