### ISSUE TITLE
NTR: spiny stellate cell morphology

### ISSUE THREAD

**Issue by shawntanzk** [pato-ontology/pato#385]
**Term:** 
spiny stellate cell morphology

**Definition:**
A cell morphology that inheres in neurons which have spiny basal dendrites and resemble pyramidal cells but lose their apical dendrites as they mature. Their axons nearly always emerge from the descending side of the soma, but often recurve and ascend with arc-like collaterals.
doi:10.1016/b978-0-12-369497-3.10004-4

**Parent Class:**
Cell Morphology #364

**Others:**
Neocortex spiny stellate: SAO:1236796660; ILX:0107391 
ilxtr:SpinyStellatePhenotype

**Comment by tgbugs** [comment]
Maybe an additional explicit note in the definition that the basal dendrites are spiny.

**Comment by dosumis** [comment]
Edited slightly for clarity.
