### ISSUE TITLE
NTR moving organismal quality terms from ecocore to PATO

### ISSUE THREAD

**Issue by diatomsRcool** [pato-ontology/pato#394]
Please see https://github.com/EcologicalSemantics/ecocore/issues/137

**Comment by cmungall** [comment]
I support this and I think it will make things simpler. I assume that organismal characteristics that apply to microbes (e.g. facultative anaerobe) will also go into PATO?

I think there is clearly precedent for these kinds of terms.

The counter argument is that PATO should be more basic characteristics that can be composed with different entities. But I think it's just the case that there are some organismal characteristics that only compose with 'organism' and PATO is the most logical home

**Comment by shawntanzk** [comment]
Terms have been merged
