### ISSUE TITLE
http://purl.obolibrary.org/obo/PATO_0001744 and children

### ISSUE THREAD

**Issue by PaulNSchofield** [pato-ontology/pato#402]
We are looking at classes for radiation exposure and looked at the above class and its children for the RBO. The problem is that the definition of this class " A radiation quality inhering in a bearer by virtue of what the bearer receives as a result of being exposed to ionizing radiation." is not so much Radiation exposure as "radiation exposed", being a property of an entity which has in the past been exposed to radiation. The class label should probably therefore be "Radiation exposed", or "Irradiated". So this isnt so much a quality of radiation as a quality of the entity irradiated. The children are another problem as they are qualities of doses of radiation and in the latter case a measurement of the effect of radiation on a given organ. In 
 a way these are qualities of two entities, radiation and irradiated entity as dose is always measured in joules ( the radiation quality)  per kilogram ( the irradiated entity quality) or some derivative. These are not simple subtypes of an "irradiated quality of an entity" and might be seen as properties of an exposure event rather than subclasses of the "quality of having been exposed to radiation". The children of "Irradiated" or Radiation exposed" should probably be something like "low-absorbed-dose radiation exposed" but Im not sure that such a  class would be useful, Radiation absorbed dose is measure in Grays - ie joules/kg, equivalent dose as energy of total dose delivered and radiation effective dose is dose qualified by some biological endpoint for a specific organ. So we are not sure that these are actually qualities of "Irradiated" or "radiation exposed" so much as qualities of an irradiation event which occurs in time. So the fundamental request is to change the label of 1744 and then to consider what might be done with its children.

**Comment by shawntanzk** [comment]
Hi @PaulNSchofield sorry I missed this before. 
Could you confirm these are the actions:

- [ ] Change PATO_0001744 label to "irradiated" or "radiation exposed"
- [ ] Move current children to more appropriate parent term
- [ ] Potentially add new subclasses of PATO_0001744  "low-absorbed-dose radiation exposed" if there is a use case - though probably not

Happy to help change the label, but regarding moving the children, I think what I can do is to put this on the agenda for a phenotype call for discussion, not sure I know what to do with the children otherwise

**Comment by rays22** [comment]
Usage?
- [ ] check it on ontobee

**Comment by PaulNSchofield** [comment]
So the original class was defined as a quality of radiation, which it is not, so we changed the definition as the intended meaning was certainly "irradiated" after asking around. From the physics point of view an object or an animal has different properties once it has been irradiated and logically this is then an acquired quality as a consequence of the input of energy. This is a one way process as you cannot "unirradiate" something and is a permanent change in the quality of a continuant, hence appropriate for PATO. It is also measurable in the organism by various methods so could also be viewed as a phenotype - a measurable characteristic - and irradiated animals show characteristic changes of several different kinds unique to their being irradiated. Its used in describing experiments where one entity is an irradiated entity, or where an object or an organism becomes irradiated as a consequence of active or accidental exposure. It could also be in the exposure ontology but its most definitely a quality and not a process. PATO contains a lot of qualities of radiation including visible light and the properties of the objects which interact with that radiation. The cognate process is irradiation and is in RBO. Does that help? Nearly all of these rearranged or modified  terms to do with radiation have been in PATO for years but some in the wrong place and some poorly defined.

**Comment by sbello** [comment]
Thanks @PaulNSchofield that makes sense. So a use case for this would be something like "irradiated tomato" which would encompass the changes in the tomato induced by radiation exposure. It would probably help to have a curation note with the term to explain the usage. 

What is the use case for the child terms or should these be obsoleted?

**Comment by shawntanzk** [comment]
I can't rmbr, have I made all the changes you requested already @PaulNSchofield 
Either way I'm going to remove myself from this thread, please ping me if there's anything I can help with :) thanks

**Comment by PaulNSchofield** [comment]
> Thanks @PaulNSchofield that makes sense. So a use case for this would be something like "irradiated tomato" which would encompass the changes in the tomato induced by radiation exposure. It would probably help to have a curation note with the term to explain the usage.
> 
> What is the use case for the child terms or should these be obsoleted?

As far as I can see there are no child terms for PATO_0001744 @sbello . I think these might have already been deprecated?

**Comment by sbello** [comment]
We were discussing this ticket at the Phenotype editors call last Thursday with relation to if the children needed to be kept but if they don't that is great. I think then we can close the ticket?

**Comment by PaulNSchofield** [comment]
agreed!
