### ISSUE TITLE
http://purl.obolibrary.org/obo/PATO_0001739 label

### ISSUE THREAD

**Issue by PaulNSchofield** [pato-ontology/pato#403]
The label for this class is somewhat confusing for a radiation scientist. The term radiation quality specifically refers to the  fluence spectrum of charged and neutral particles (particle types and energies) of the incident radiation AT the target. This is not what is meant here where I think the definition suggests that it is a quality of the irradiated entity and not the radiation. 

"A quality that inheres in an bearer by virtue of how that bearer interacts with radiation."

A label that might better reflect the definition might be "Irradiated quality", "Radiation target quality" or possibly "Irradiated entity quality"

**Comment by shawntanzk** [comment]
@PaulNSchofield is this addressed by the change of definition in https://github.com/pato-ontology/pato/pull/487 or should we still change the label?

**Comment by PaulNSchofield** [comment]
Hope the above addresses this @shawntanzk .

**Comment by shawntanzk** [comment]
Fixed by https://github.com/pato-ontology/pato/pull/487 - please reopen or create a new issue if there are still issues on this
