### ISSUE TITLE
NTR: cell with bitufted dendrite morphology

### ISSUE THREAD

**Issue by shawntanzk** [pato-ontology/pato#415]
Preferred term label:
cell with bitufted dendrite morphology

Definition:
A cell morphology that inheres in neurons with dendrites that are bidirectional, emerging from opposite ends of the soma, with the two arbors extending in radial or tangential directions. (PMID: 18568015)

Parent term:
Cell morphology 
_Note: Bipolar and bitufted should be asserted under this_

related to #414

**Comment by dosumis** [comment]
I don't understand the need for this term when we already have bitufted.  Can you explain further?

> Preferred term label:
> cell with bitufted dendrite morphology

This is a morphology term, but the name makes it sound like a cell type.

> 
> Definition:
> A cell morphology that inheres in neurons with dendrites that are bidirectional, emerging from opposite ends of the soma, with the two arbors extending in radial or tangential directions. (PMID: 18568015)

The radial vs tangential thing is, I suspect, cortex specific.

> 
> Parent term:
> Cell morphology
> Note: Bipolar and bitufted should be asserted under this

Bipolar can't be under here - that applies to cells with axon & dendrite emerging from opposite ends of the soma.

**Comment by shawntanzk** [comment]
> I don't understand the need for this term when we already have bitufted. Can you explain further?

Think this is a way to differentiate bitufted cell mophology from bitufted dendrite which refer to two different things (see discussion on closed PR #413) bitufted dendrite being dendrites that emerge from both sides including bipolar and double boquet cells, though the point on Bipolar having dendrite and axon on opposite side is a good one. Thoughts on this @tgbugs?

**Comment by tgbugs** [comment]
I think we should included an editor note or similar to explain exactly why we need this due to the confusing nature of the original nomenclature where there is a cell type that has the same name as a dendrite type but the cell type with the name is a specific subset of the cells with the dendrite type.

**Comment by shawntanzk** [comment]
> Bipolar can't be under here - that applies to cells with axon & dendrite emerging from opposite ends of the soma.

@tgbugs wondered what your thoughts on this are - currently bipolar is asserted under cell with bitufted dendrite morphology, however @dosumis makes a good point that bipolar cells have one end being axons, while the other being dendrite, hence not technically falling under cell with bitufted dendrite morphology.

**Comment by tgbugs** [comment]
There is some confusion here. When I check the Petilla paper (which is what the NPO terms correspond most closely to) https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2868386/ I see this in the dendrites section:

> The polarity of the dendritic arborization16 can be described (FIG. 1a–h; Supplementary information S5). ‘Unipolar’, ‘bipolar’ and ‘multipolar’ cells have one, two or multiple long primary dendrites, respectively, extending from their cell body17,18. ‘Bitufted’ cells have two clusters of branches that originate directly from the soma and extend in opposite directions19. In any interneuron with bidirectional dendrites (be it bipolar or bitufted), the two arbors can extend in radial or tangential directions.

We likely have to distinguish between retinal bipolar cells which are as @dosumis states, and cortical bipolar cells, which are different.

**Comment by shawntanzk** [comment]
Thanks for the clarification @tgbugs 
I've made the following changes in the PR #416 
1.  Changed bipolar morphology to cortical bipolar morphology
2. Changed def of cortical bipolar morphology to state specifically dendrite
3. Added comment to state that is distinguished from retinal bipolar morphology
4. Added a new term retinal bipolar morphology
