### ISSUE TITLE
Rename "originates from" to include position

### ISSUE THREAD

**Issue by ddooley** [pato-ontology/pato#435]
The "position" qualities encode spatial object relations, which is fine, though it suggests that many of those qualities attach between objects in a complementary way, essentially encoding mereotopology into qualities ( e.g. 'adjacent to' - "A has quality 'adjacent to' [has value] value B" and visa versa). But I'm just interested in "originates from" whose label belies a more specific meaning - its positional quality. Perhaps that quality could be renamed "position originates from" or "originates from position"? 

My motivation is that FoodOn is considering asking for an object relation "originates from" that connects between an entity and another entity it originates from via some processing or no processing at all.

**Comment by shawntanzk** [comment]
Hi @ddooley, was asked to help be the first pass (resolving issues if I can, if not assigning it to someone who can) for PATO. 
So, from my understand of your ticket, your ideal fix would be to change PATO:0040002 label from "originates from" to "position originates from" so that you can have another term that is "originates from" that is not related to position right?

**Comment by shawntanzk** [comment]
@dosumis is there a protocol to change labels or do we just go ahead and do so? I worry because usually I would add the previous label as synonym, but this would be tricky as there will eventually be another "originates from". Happy to just make the label change if that's alright?

**Comment by dosumis** [comment]
@shawntanzk  - just add a clarifying

**Comment by shawntanzk** [comment]
@ddooley could you help me take a look if this is ideal for you please? thanks 
https://github.com/pato-ontology/pato/pull/436

**Comment by ddooley** [comment]
Great, thanks!
