### ISSUE TITLE
Cleaning Object Properties in PATO

### ISSUE THREAD

**Issue by shawntanzk** [pato-ontology/pato#454]
PATO currently probably uses non-RO terms for relations when they should be RO (from the report): 
see http://dashboard.obofoundry.org/dashboard/pato/fp7.html 
This needs to be fixed by replacing them with RO terms
@shawntanzk to investigate 

EDIT: Also, Object Properties should not be using mnemonic names (like RO:towards), see also https://github.com/pato-ontology/pato/issues/355, but real ids like RO:001

**Comment by shawntanzk** [comment]
PATO seems to use weird purls for a whole bunch of relations, this should be replaced by RO terms
Will import terms into RO and change the IRIs to point to RO purls instead

**Comment by shawntanzk** [comment]
mappings:

towards > RO:0002503
correlates_with > RO:0002610

decreased_in_magnitude_relative_to > These bunch have no RO term, might have to also look individual case basis? 
different_in_magnitude_relative_to > perhaps using RO:0002424 (differs in) 
similar_in_magnitude_relative_to >
increased_in_magnitude_relative_to >
has_relative_magnitude >

directly_associated_with > based on magnitude too, not in RO, but it doesnt seem to be used in PATO atm? 
has_cross_section > don't think theres a RO term that describes this well
has_dividend_entity > not sure what this is and it isnt used in PATO
has_dividend_quality > not sure what this is and it isnt used in PATO
has_divisor_entity > not sure what this is and it isnt used in PATO
has_divisor_quality > not sure what this is and it isnt used in PATO
has_ratio_quality > not sure what this is and it isnt used in PATO
inversely_associated_with > seems to have to do with magnitude, not sure there's a good mapping
is_magnitude_of > not sure what this is and it isnt used in PATO
is_measurement_of > not sure what this is and it isnt used in PATO
is_unit_of > not sure what this is and it isnt used in PATO
realized_by > not sure what this is and it isnt used in PATO

reciprocal_of > technically sounds like RO:HOM000060 (in apparent orthology relationship with) but the RO term is specific to species homology 

singly_occurring_form_of > seems a bit specific to PATO?

**Comment by shawntanzk** [comment]
@cmungall I noticed that a lot of these terms were added by you - was wondering if these should move to RO or there's a reason to keep them specific to PATO?

**Comment by anitacaron** [comment]
Nico will contact Chris on Slack.

**Comment by matentzn** [comment]
Did. pato slack on obo-community

**Comment by cmungall** [comment]
If they are useful, move them to RO

Some are used in TO, we need to align TO patterns with upheno

**Comment by shawntanzk** [comment]
> If they are useful, move them to RO

@cmungall does useful = actually used in PATO or like generally useful? 
Happy to try to bit by bit sort this out and migrate to RO

**Comment by matentzn** [comment]
This is a great question @shawntanzk 

I would do this:

Check on OLS whether a relation is used somewhere:

https://www.ebi.ac.uk/ols/search?q=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2Fpato%23has_divisor_entity&groupField=iri&exact=on&start=0

For example, has_divisor_entity is used by FLOPO, MS and PATO:

![image](https://user-images.githubusercontent.com/7070631/144196774-87b9df1e-7061-491b-bec7-5c7f2f223590.png)

Curate your list above to look like this:

- [has_divisor_entity](https://www.ebi.ac.uk/ols/search?q=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2Fpato%23has_divisor_entity&groupField=iri&exact=on&start=0): FLOPO, MS, PATO
- ....

Then in our tech goal, we can decide to obsolete some relations, or move them to RO.

**Comment by matentzn** [comment]
And dont spend much time, remember: open ontology work is super exciting and important, but it is a time suck: better we make tiny constant progress then to have someone like @dosumis pull the plug because we get to carried away fixing things that are only tangentially related to our respective projects.

**Comment by shawntanzk** [comment]
http://purl.obolibrary.org/obo/pato#towards – XPO, FLOPO, HP, MP, MS, PHIPO, WBPhenotype, ZP

http://purl.obolibrary.org/obo/pato#correlates_with – PLANP, FBcv FLOPO, MP, MS, WBPhenotype, XPO, ZP

http://purl.obolibrary.org/obo/pato#decreased_in_magnitude_relative_to – PLANP, AISM, CL, CMPO, ECTO, EFO, FBcv FLOPO, FYPO, HCAO, HP, MAXO, MONDO, MP, MS, NBO, ONTONEO, PCO, PHIPO, TO WBPhenotype, XPO, ZP

http://purl.obolibrary.org/obo/pato#different_in_magnitude_relative_to – PLANP, AISM, CL, CMPO, ECTO, FBcv, FLOPO, FYPO, HCAO, HP, MAXO, MONDO, MP, MS, NBO, ONTONEO, PCO, PHIPO, TO, WBPhenotype, XPO, ZP

http://purl.obolibrary.org/obo/pato#similar_in_magnitude_relative_to – CMPO, AISM, FLOPO, MS

http://purl.obolibrary.org/obo/pato#increased_in_magnitude_relative_to – PLANP, AISM, CL, CMPO, ECTO, EFO, FBcv, FLOPO, FYPO, HCAO, HP, MAXO, MONDO, MP, MS, NBO, ONTONEO, PCO, PHIPO, TO, WBPhenotype, XPO, ZP

http://purl.obolibrary.org/obo/pato#has_relative_magnitude – PHIPO, CL, FLOPO, HCAO, MS, ZP

http://purl.obolibrary.org/obo/pato#directly_associated_with – CMPO, FLOPO, MS

http://purl.obolibrary.org/obo/pato#has_cross_section – PALNP, AISM, CL, CMPO, FLOPO, FYPO, HCAO, HP, MAXO, MONDO, MP, MS, TO, WBPhenotype, XPO, ZP

http://purl.obolibrary.org/obo/pato#has_dividend_entity – FLOPO, MS

http://purl.obolibrary.org/obo/pato#has_dividend_quality – CMPO, FLOPO, MS

http://purl.obolibrary.org/obo/pato#has_divisor_entity – FLOPO, MS

http://purl.obolibrary.org/obo/pato#has_divisor_quality – CMPO, FLOPO, MS

http://purl.obolibrary.org/obo/pato#has_ratio_quality – CMPO, FLOPO, MS

http://purl.obolibrary.org/obo/pato#inversely_associated_with – CMPO, FLOPO, MS

http://purl.obolibrary.org/obo/pato#is_magnitude_of – FLOPO, MS

http://purl.obolibrary.org/obo/pato#is_measurement_of – FLOPO, MS

http://purl.obolibrary.org/obo/pato#is_unit_of – FLOPO, MS

http://purl.obolibrary.org/obo/pato#realized_by – FLOPO, MS

http://purl.obolibrary.org/obo/pato#reciprocal_of – PLANP, AGRO, AISM, CMPO, ECTO, FBcv, FLOPO, FYPO, HP, MAXO, MONDO, MP, MS, NBO, ONTONEO, PCO, PHIPO, TO, WBPhenotype, XPO, ZP

http://purl.obolibrary.org/obo/pato#singly_occurring_form_of – FLOPO, MS

**Comment by anitacaron** [comment]
@matentzn will discuss with Chris

**Comment by matentzn** [comment]
Usage API

SPLIT into to

1) Useful in PATO for modeling 
2) Design patterns for PATO
3) Some of them are used in general design patterns (plant people xyz) - 

finish later

**Comment by matentzn** [comment]
I have updated @shawntanzk comment above with the proposed actions.

**Comment by shawntanzk** [comment]
http://purl.obolibrary.org/obo/pato#correlates_with - this is currently being used, but also, it can be mapped to a RO term (https://www.ebi.ac.uk/ols/ontologies/ro/properties?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FRO_0002610) - will map instead

**Comment by shawntanzk** [comment]
For realized by, I have decided to deprecate it and leave a comment and term replaced by (it is current not being used and the RO term is not exact)

**Comment by balhoff** [comment]
@shawntanzk to answer your question above, I do think numerical IDs for those properties would be good.

**Comment by shawntanzk** [comment]
> @shawntanzk to answer your question above, I do think numerical IDs for those properties would be good.

@balhoff - I guess the question then is if they belong in RO? or should we do it like the old CP terms in CL and convert them to PATO IRIs?

**Comment by matentzn** [comment]
Every OP in RO!

**Comment by shawntanzk** [comment]
Mapping to new RO terms (will map when they are out in RO):
 http://purl.obolibrary.org/obo/pato#decreased_in_magnitude_relative_to – RO:0015008
 http://purl.obolibrary.org/obo/pato#different_in_magnitude_relative_to – RO:0015006
 http://purl.obolibrary.org/obo/pato#similar_in_magnitude_relative_to – RO:0015009
 http://purl.obolibrary.org/obo/pato#increased_in_magnitude_relative_to – RO:0015007
 http://purl.obolibrary.org/obo/pato#has_relative_magnitude – RO:0015010
 http://purl.obolibrary.org/obo/pato#has_cross_section – RO:0015011
 http://purl.obolibrary.org/obo/pato#reciprocal_of – RO:0015012

**Comment by LarsVogt** [comment]
Hi,
we have a case in a material science project where we want to be able to model proportions/ratios by relating the dividend value to the divisor value (e.g. density as the ratio of mass over volume). I used pato:hasDividendQuality and pato:hasDivisorQuality for this before but it now neither in PATO nor in RO. Any chance to get them back or an adequate replacement?

**Comment by matentzn** [comment]
Absolutely, can you make a new relation request in RO for these relations, link this issue and ask @anitacaron for help adding it?
