### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by matentzn** [pato-ontology/pato#478]
Some definition on synovial cell causes problems for MP, which is not yet on base 

- [ ] https://github.com/mgijax/mammalian-phenotype-ontology/issues/3521

@shawntanzk if you could do a release soonish that would be great, if not, I can do it too.

**Comment by shawntanzk** [comment]
happy to run one, stuck inside today anyway cause of rain :( I'm guessing it needs IMP to be refreshed too?

**Comment by matentzn** [comment]
Yeah probably the entire thing IMP MIR both true! Thank you! :)

**Comment by shawntanzk** [comment]
it seems that running `prepare_release` didnt update merged imports - am now making it separately instead, but thought it might be something to look into

**Comment by matentzn** [comment]
`prepare_release` did not update merged imports?  in any case, this pointed me to a missing link in the dependencies, so good observe, thanks @shawntanzk

**Comment by shawntanzk** [comment]
> prepare_release did not update merged imports? 

Yups, had to run it separately.
