### ISSUE TITLE
Create terms 'male with DSD' and 'female with DSD'

### ISSUE THREAD

**Issue by KaylaPenn** [pato-ontology/pato#482]
Individuals with congenital physical disorders of sexual development (DSD; the term 'intersex' is more commonly known, but is a misnomer as people with DSD are not between sexes, a third sex or hermaphrodites) are not represented under male [PATO_0000384] or female [PATO_0000383]. These conditions can be valuable classifiers when relevant and are not the same as later changing natal/naturally-developed sexual characteristics (ie, castration [PATO_0002367] or spaying [PATO_0040020]).

Sources:
https://www.karger.com/Article/FullText/499274
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5866176/

**Comment by shawntanzk** [comment]
Hi @KaylaPenn, 

thanks for the ticket, we will look into this and try to get the terms added.

@nicolevasilevsky - not sure if you want to handle this? I'm happy to, but it might take me a bit of time to get to this. I'll assign it to myself for now, but if you want to take it please do assign yourself too. Thanks!

**Comment by nicolevasilevsky** [comment]
I can do it! Thanks @shawntanzk

**Comment by nicolevasilevsky** [comment]
@KaylaPenn what are the specific terms that you'd like us to add? Could you please share the term label, any synonyms and a suggested definition?
Thank you!

**Comment by KaylaPenn** [comment]
I defer to what you think is best. I suggest the following, but it doesn't translate well for non-animals:

**'male with DSD'** or **'male, DSD'** = an otherwise male individual of a non-hermaphroditic species who has ambiguous or atypical congenital development of genetics, genitals and/or gonads

**'female with DSD'** or **'female, DSD'** = an otherwise female individual of a non-hermaphroditic species who has ambiguous or atypical congenital development of genetics, genitals and/or gonads

**'intersex'** could serve as a synonym for both as it's still in popular use, but may be considered offensive in some circles when applied to humans. DSD can be expanded multiple ways to 'disorders/differences of sexual development/differentiation'.

Thank you!

**Comment by nicolevasilevsky** [comment]
thanks @KaylaPenn and @sbello. I'll start this on a PR and folks can weigh in. 
Beautiful graphics in that SA article!

**Comment by nicolevasilevsky** [comment]
@KaylaPenn do you have an ORCID?

**Comment by KaylaPenn** [comment]
> @KaylaPenn do you have an ORCID?

0000-0001-5193-0062

**Comment by KaylaPenn** [comment]
Fun fact I learned from someone more knowledgeable: 'dioecious' (mostly applied to plants) and 'gonochoric' (mostly applied to animals) are antonyms for 'hermaphroditic'

**Comment by KaylaPenn** [comment]
I will not operate this GitHub account after July 20th. Please contact Dr. Ruth Timme (https://github.com/retimme) for any further questions or comments. Thank you.
