### ISSUE TITLE
Change definition of PATO_0001739 Radiation Quality

### ISSUE THREAD

**Issue by PaulNSchofield** [pato-ontology/pato#484]
Radiation quality is a property inhering in the radiation energy and not in the entity or medium exposed to the radiation. 

**New definition:**
Is a quality of radiation that reflects the fluence spectrum of charged and neutral particles within the material or medium where dose is being deposited.

**Citation**
https://melodi-online.eu/wp-content/uploads/2021/04/02-What-is-radiation-quality-Goodhead.pdf

**Comment:**
Radiation quality is often expressed in terms of the linear energy transfer of the ionising particles that deliver the absorbed dose. Rossi, Harald H. “Specification of Radiation Quality.” Radiation Research, vol. 10, no. 5, Radiation Research Society, 1959, pp. 522–31, https://doi.org/10.2307/3570787. But this is an over simplification.

This remains a quality of a physical  entity but the children need some attention.

**Comment by shawntanzk** [comment]
Hi @PaulNSchofield - wondering if you had a better citation for it, a linked pdf doesn't seem to be the most stable thing. 
Could you also provide your ORCID so I can credit you with the changes proposed? Thanks

**Comment by PaulNSchofield** [comment]
It’s pretty stable as that is the website of a large European project. The document is the only critical appraisal of the issue unfortunately and most other sources get it wrong. However I’ll deposit in in the Store database and it will get a doi. Store is completely stable. German federal resource. I’ll get my orcid to you as soon as I get back to my laptop.


Cheers

P

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by PaulNSchofield** [comment]
ORCID: 0000-0002-5111-7263

**Comment by PaulNSchofield** [comment]
This DOI should be live soon: [DOI:10.20348/STOREDB/1173/1250](http://dx.doi.org/doi:10.20348/STOREDB/1173/1250)
There is also an accession ID.. [STOREDB:STUDY1173](https://www.storedb.org/?STOREDB:STUDY1173)
STORE is registered with Re3DATA and identifiers.org

**Comment by shawntanzk** [comment]
thanks heaps will make the edits :)

**Comment by PaulNSchofield** [comment]
Cheers! Much appreciate how fast you have done this!

I will get a few more classes in this are oof the ontology under consideration soon along with my colleagues at NASA,


Cheers,

Paul


Dr Paul Schofield MA D.Phil FRSB

Professor of Biomedical Informatics, University of Cambridge.
Department of Physiology, Development and Neuroscience,
Downing Street, Cambridge CB2 3EG. UK

Fellow, The Alan Turing Institute

Adjunct Professor,The Jackson Laboratory,
600, Main Street, Bar Harbor,  ME 04609, USA

ORCID: 0000-0002-5111-7263

Fellow, Robinson College,
Cambridge, CB3 9AN UK


Direct line: Dept.+44-1223-333878
College. +44-1223-768887
Fax:            +44-1223-333840


***@***.***

On 4 Apr 2022, at 13:53, Shawn Tan ***@***.******@***.***>> wrote:


thanks heaps will make the edits :)

**Comment by PaulNSchofield** [comment]
We had further discussions about the impact of the change of definition on the existing child terms and the local ontology structure yesterday. In the light of this , and apologies for asking for a tweak to the changes we suggest that:
1. The definition is changed ( @shawntanzk I know that you have done this, thanks!) and the parent should be Physical quality (PATO:0001018)
2.electromagnetic (EM) radiation quality (PATO:0001291) is deprecated
3. A new class is made to replace 0001291 - 
New Class: "Quality of interaction of a substance with electromagnetic radiation"
Definition: "A quality of a substance on which or through which electromagnetic radiation impinges or traverses with respect to  radiation". I think the parent should be "Quality of a substance" PATO_0002198 as all these qualities are those of a physical entity which could be a liquid solid or gas. We think this new term covers all of the subtree currently under "Electromagnetic radiation quality"
4. Similarly "activity of a radionuclide" PATO_0001740 should be moved to being a quality of a substance.

We think that this then leaves this subtree correct and consistent. There is an envo class http://purl.obolibrary.org/obo/ENVO_03510037 radioactive material that is related to 0001740 which might be worth cross referencing.
