### ISSUE TITLE
deprecate PATO_0001744 Radiation exposure and replace

### ISSUE THREAD

**Issue by PaulNSchofield** [pato-ontology/pato#485]
Radiation exposure is a process and does not conform to the definition given. This would best be deprecated and replaced with

**Label:** Irradiated
**Definition:** A quality inhering in a bearer by virtue of the bearer being exposed to electromagnetic, usually ionising, radiation.
**Parent:** PATO_0001241 Physical object quality
**Comments:** Irradiation may be external or in the case of an organism, internal from ingested or otherwise absorbed radioactive material.

**Comment by shawntanzk** [comment]
Hi @PaulNSchofield would you suggest that the child nodes under radiation exposure be moved to child of irradiated too? From the definition you have given, could I suggest that instead of depercating radiation exposure, we move it to a physical object quality, change the label to irradiated, and use radiation exposure as a related synonym? I would think that most people refer to irradiated when using radiation exposure (correct me if im wrong, I'm not in the field and all) Thanks

**Comment by shawntanzk** [comment]
Ah ok, got it. 
Happy to make the changes, but given I know just about nothing about radiation, would be good if you could provide me the following:
1) Names, definitions (and associated references), synonyms, superclass (which you have already provided) of the two terms to be added 
2) for deprecation of PATO:0001745, PATO:0001747, PATO:0001746, it would be good if I could get their relevant replacements in RBO so I can add a replaced_by or consider axiom there for anyone coming across it to be redirected to RBO
Thanks

**Comment by PaulNSchofield** [comment]
We are agreed on the suggestions above:
1. add a new class "Irradiated" with a synonym "radiation exposed". 
Definition: "A quality of a substance currently or previously exposed to electromagnetic radiation"
Comments: " This may refer to incident external irradiation or internal radiation from an ingested or otherwise internal source"
Reference: Radiobiology for the Radiologist ( 2018) Eric J. Hall DPhil, DSc, FACR, FRCR, Amato J. Giaccia, SBN/ISSN:
9781496335418. Wolters/Kluwer .
2. Add new class : Radiation exposure - child of "process" 
Defined as:  "The planned or incidental exposure of an entity to electromagnetic radiation"
Comments: This refers to the planned or unplanned process by which an entity is exposed to radiation either externally or from an internalised source.
Reference: same as above. These are very basic concepts.

 We do have Radiation exposure in RBO - RBO:00002000 but I think that under the circumstances rather than import it from RBO Id leave it in PATO and assert equivalence. You could DXRef.

The three children should be deprecated and suggest using:

PATO:0001745 : RBO:00005010
PATO:0001747: RBO:00000014
PATO:0001746: RBO:00000023
Hope this all makes sense!

**Comment by shawntanzk** [comment]
Hi @PaulNSchofield I'm looking at the definition of radiation exposure and it is similar to that of irradiated, I've hence opted to keep the ID but change the label, axioms, and def accordingly, hope that is alright

**Comment by shawntanzk** [comment]
I'm also not sure what the difference between irradiated and quality of interaction of a substance with electromagnetic radiation is?

**Comment by shawntanzk** [comment]
> Add new class : Radiation exposure - child of "process"

I'm not 100% sure PATO deals with actual processes, rather just quality of the process.

**Comment by PaulNSchofield** [comment]
@shawntanzk you are correct! My  internal BFO is getting confused. Radiation exposure should not be in PATO as its a process and not a quality. We now have "Irradiated" which of course is a quality.. I think we should deprecate and recommend using RBO_00002000 Radiation exposure. Im so sorry that this has all been very confusing....combination of dealing with two ontologies at a time and looking at the consequences of taking classes aout and moving them around. Entirely my fault.
