### ISSUE TITLE
'hyperplastic' should be defined by cell number rather than size

### ISSUE THREAD

**Issue by Clare72** [pato-ontology/pato#489]
Discussed in phenotype ontology editors' call 02/24/22

'hyperplastic' - PATO:0000644 is currently defined to be an increase in size, but this is not always the case (if the cells are smaller). It should instead be defined as an increase in the number of cells.

A similar change should be made to 'hypoplastic' - PATO:0000645

**Comment by shawntanzk** [comment]
Hi @Clare72, I'm currently shepherding PATO (triaging tickets). Are you happy to make the changes yourself/can I assign this ticket to you? Thanks

**Comment by Clare72** [comment]
This may need further discussion, as it is not immediately clear where to move the terms to - there is no 'increased cell number' term (yet). Perhaps just under 'increased object quality'? @dosumis ?
