### ISSUE TITLE
Electromagnetic (EM) radiation quality ( PATO:0001291) and subtree

### ISSUE THREAD

**Issue by PaulNSchofield** [pato-ontology/pato#490]
We had further discussions about the impact of the change of definition on the existing child terms and the local ontology structure yesterday. In the light of this , and apologies for asking for a tweak to the changes we suggest that:

1. The definition of Radiation quality is changed ( @shawntanzk I know that you have done this, thanks!) and the parent should be Physical quality (PATO:0001018)
2.electromagnetic (EM) radiation quality (PATO:0001291) is deprecated
A new class is made to replace 0001291 -
New Class: "Quality of interaction of a substance with electromagnetic radiation"
Definition: "A quality of a substance on which or through which electromagnetic radiation impinges or traverses with respect to radiation. This substance quality changes the quality of the incident radiation with respect to any of: intensity, direction, scatter and wavelength". I think the parent should be "Quality of a substance" PATO_0002198 as all these qualities are those of a physical entity which could be a liquid solid or gas. We think this new term covers all of the subtree currently under "Electromagnetic radiation quality" without having to change it.
3. Similarly "activity of a radionuclide" PATO_0001740 should be moved to being a "quality of a substance."
We think that this then leaves this subtree correct and consistent. There is an envo class http://purl.obolibrary.org/obo/ENVO_03510037 radioactive material that is related to 0001740 which might be worth cross referencing.

**Comment by shawntanzk** [comment]
@PaulNSchofield whoops, missed that, will do

**Comment by PaulNSchofield** [comment]
We checked out the version on the branch at our meeting today and all looks good, so happy to merge. Any idea when the next release will be as we will need that to happen before we can do our next build and pull in the new PATO changes? Thanks!!

**Comment by shawntanzk** [comment]
I can push out a release tomorrow. Will let you know when I do :) thanks
