### ISSUE TITLE
Clarify in PATO the distinction between mislocalised and dislocated

### ISSUE THREAD

**Issue by rays22** [pato-ontology/pato#501]
Clarify the distinction between [mislocalised PATO:0000628](https://www.ebi.ac.uk/ols/ontologies/pato/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPATO_0000628) and [dislocated PATO:0001852](https://www.ebi.ac.uk/ols/ontologies/pato/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPATO_0001852).
See [comment]((https://github.com/obophenotype/upheno/pull/829#issuecomment-1138747275)

* [position PATO:0000140](https://www.ebi.ac.uk/ols/ontologies/pato/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPATO_0000140&lang=en&viewMode=PreferredRoots&siblings=false) A spatial quality inhering in a bearer by virtue of the bearer's spatial location relative to other objects in the vicinity.
    * [displaced PATO:0002181](https://www.ebi.ac.uk/ols/ontologies/pato/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPATO_0002181&lang=en&viewMode=PreferredRoots&siblings=false) A positional quality inhering in a bearer by virtue the bearer's being changed in position.
        * [mislocalised PATO:0000628](https://www.ebi.ac.uk/ols/ontologies/pato/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPATO_0000628) A positional quality inhering in a bearer by virtue the bearer's being changed in abnormal position.
        * [dislocated PATO:0001852](https://www.ebi.ac.uk/ols/ontologies/pato/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPATO_0001852) A positional quality inhering in a bearer by virtue of the bearer's being out of its usual or proper place, or position.

**Comment by rays22** [comment]
- [ ] need a report of usage of
[mislocalised PATO:0000628](https://www.ebi.ac.uk/ols/ontologies/pato/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPATO_0000628) A positional quality inhering in a bearer by virtue the bearer's being changed in abnormal position.
[dislocated PATO:0001852](https://www.ebi.ac.uk/ols/ontologies/pato/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPATO_0001852) A positional quality inhering in a bearer by virtue of the bearer's being out of its usual or proper place, or position.

**Comment by dosumis** [comment]
Ticket can be closed on merge #503. New issue https://github.com/pato-ontology/pato/issues/505
