### ISSUE TITLE
[NTR] bistratified dendrite morphology 

### ISSUE THREAD

**Issue by shawntanzk** [pato-ontology/pato#531]
Label: bistratified dendrite cell morphology 
Superclass: PATO:0010006 ('cell morphology')
Definition: A cell morphology that inheres in neurons with dendrites that stratifies at two and only two locations. [PMID:34093409]

Context: useful for defining cells in https://github.com/obophenotype/cell-ontology/pull/1713 -> currently uses bilateral, which is causing unsats

@dosumis & @patrick-lloyd-ray - I think this should/might need a link to bilateral somehow, but I'm not sure how or if there is a reason to do so? any input would be much appreciated :)

**Comment by patrick-lloyd-ray** [comment]
I don't see the utility in linking to 'bilateral' here, but perhaps I'm not thinking through all of the possible use cases.

**Comment by shawntanzk** [comment]
> I don't see the utility in linking to 'bilateral' here

Agreed - I was  just wondering if there was utility given it was used previously, will make a PR without it then :) thanks!
