### ISSUE TITLE
restructure amount

### ISSUE THREAD

**Issue by sbello** [pato-ontology/pato#554]
From the UPheno call on Jan, 26 2024
Request changes to PATO

- [x] Create a quantitative branch
- [x] Move amount under this
- [x] Make concentration a child of amount
- [x] Remove reciprocal relation to ‘has number of’
- [x] Make has number of a child of amount

See minutes https://docs.google.com/document/d/1WrQanAMuccS-oaoAIb9yWQAd4Rvy3R3mU01v9wHbriM/edit?usp=sharing

**Comment by sbello** [comment]
Would also be good to define qualitative

**Comment by rays22** [comment]
* quantitative
Proposed textual definition: *A quality relating to an amount that can be measured or counted.
