### ISSUE TITLE
NTR: Flared

### ISSUE THREAD

**Issue by laurajackson** [pato-ontology/pato#57]
def: A shape quality inhering in a bearer by virtue of the bearer being expanded laterally and or opened outward in shape.

is_a: shape

Flared is currently a synonym of splayed, but flared does not imply any type of curvature.
Remove synonym from splayed

-Laura

**Comment by nicolevasilevsky** [comment]
If there are no objections, I'll add this next week

**Comment by nicolevasilevsky** [comment]
@laurajackson what is your ORCID? I'll add it to the new class.

**Comment by nicolevasilevsky** [comment]
looks like this has been added: PATO:0040022 flared

and flared is no longer a synonym of splayed.

Closing.
