### ISSUE TITLE
Transfer this repo to github.com/obophenotype

### ISSUE THREAD

**Issue by cmungall** [pato-ontology/pato#64]
Note that we already have a fork here:

https://github.com/obophenotype/pato

This was created to give a wider range of people the ability to edit the ontology, yet have a mechanism for validating and bringing these into the source version. We ended up pointing obo central at this. But this is confusing as tickets end up coming in on the @gkoutos repo.

I propose the following:
1. delete https://github.com/obophenotype/pato
2. transfer https://github.com/gkoutos/pato --> https://github.com/obophenotype/pato
3. Create a pato team with full rights on this repo that would include @gkoutos @mellybelly @dosumis @rlwalls2008 
4. update registries etc

Note that people would still be free to fork the repo and make PRs

**Comment by rlwalls2008** [comment]
This sounds like a good idea.
