### ISSUE TITLE
hardness vs flexibility 

### ISSUE THREAD

**Issue by austinmeier** [pato-ontology/pato#80]
Both harness (PATO:0000048) and flexibility (PATO:0001543) share the same definition:

"A physical quality inhering in a bearer by virtue of the bearer's disposition to being turned, bowed, or twisted without breaking"

Requesting that hardness definition be changed to reflect its true meaning.

dictionary def'n of hard: solid, firm, and resistant to pressure; not easily broken, bent, or pierced.

**Comment by shawntanzk** [comment]
Defs look different now: 
hardness: A physical quality inhering in a bearer by virtue of the bearer's resistance to pressure, being broken, or pierced.
flexibility: A physical quality inhering in a bearer by virtue of the bearer's disposition to being turned, bowed, or twisted without breaking.
