### ISSUE TITLE
NTR: Spayed female

### ISSUE THREAD

**Issue by davidrichardson** [pato-ontology/pato#83]
Definition: Female quality of being incapable to reproduce because of functional loss of the ovaries and/or uterus from surgical removal
Parent: Female PATO:0000383

**Comment by nicolevasilevsky** [comment]
any objections to adding this?

If not, I'll add it next week

**Comment by cmungall** [comment]
Surgical procedures seem out of place - can you tell us more about your use case @davidrichardson ?

**Comment by davidrichardson** [comment]
@cmungall if I remember correctly, while drawing up the FAANG metadata specification we noticed that there was an entry for castrated male (PATO:0002367), but no equivalent for female animals. There was some interest in using such a term at the time, but I've not been involved in the project for several years.

**Comment by cmungall** [comment]
in that case let's go ahead and add it for symmetry.

**Comment by davidrichardson** [comment]
Thanks @cmungall & @nicolevasilevsky
