### ISSUE TITLE
Definition review: permeable

### ISSUE THREAD

**Issue by pbuttigieg** [pato-ontology/pato#93]
It seems that [permeable](http://purl.obolibrary.org/obo/PATO_0000982) and [impermeable](http://purl.obolibrary.org/obo/PATO_0000983) refer only to liquids. It would be useful if their definitions also included permeability to gases. This would allow subclasses like "permeable to gas" to make sense: currently, that could violate the superclass constraints.

**Comment by cmungall** [comment]
need to review how `porosity` differs
